![Logo](https://www.up.edu.mx/wp-content/themes/panamericana/img/logo-footer.png)

# **Tarea 7: Regresión Multiple**

## **Asignatura:** Econometría  
## **Profesora:** Mae. Julieta María Sarralde Vera

---

**Nombre del Alumno:**  
Luis Enrique Noguera Gil

**Fecha de entrega:**  
08 de septiembre de 2024


# Auto reload modules

In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
import scripts.index as index
import numpy as np
import fs

# Ejercicio 1

Las ventas de unidades USB flash portátiles (en miles) en México son explicadas mediante un modelo de regresión múltiple. Las variables a considerar son:

- $X_1$: Las computadoras personales de escritorio vendidas (en millones de unidades).
- $X_2$: Las computadoras portátiles vendidas (en millones de unidades).
- $X_3$: El aumento porcentual en el precio del software (expresado en decimales).
- $X_4$: El número de computadoras por cada 100 mexicanos.

El tamaño de la muestra es de 150 observaciones.

Las matrices del modelo son las siguientes:

**Matriz $(X^TX)^{-1}$:**

$$
\begin{bmatrix}
2.09422 & -0.01628 & -0.77374 & 0.18777 & -0.06644 \\
-0.01628 & 0.00023 & 0.00585 & -0.00934 & 0.00062 \\
-0.77374 & 0.00585 & 0.3562 & -0.1027 & 0.01925 \\
0.18777 & -0.00934 & -0.1027 & 1.70377 & -0.0662 \\
-0.06644 & 0.00062 & 0.01925 & -0.0662 & 0.00618
\end{bmatrix}
$$

**Matriz $X^TY$:**

$$
\begin{bmatrix}
3,311.00 \\
100,691.00 \\
3,580.80 \\
1,876.26 \\
41,978.00
\end{bmatrix}
$$


In [2]:
# Matriz X^TY
XTY = np.array([
    [3311.00],
    [100691.00],
    [3580.80],
    [1876.26],
    [41978.00]
])

# Matriz (X^TX)^{-1}
XTX_inv = np.array([
    [2.09422, -0.01628, -0.77374, 0.18777, -0.06644],
    [-0.01628, 0.00023, 0.00585, -0.00934, 0.00062],
    [-0.77374, 0.00585, 0.3562, -0.1027, 0.01925],
    [0.18777, -0.00934, -0.1027, 1.70377, -0.0662],
    [-0.06644, 0.00062, 0.01925, -0.0662, 0.00618]
])

Si los estimadores por MCO se calculan con:

$\hat{\beta} = (X^T X)^{-1} X^T Y$

¿Cual es el valor del coeficiente asociado a la variable número de computadoras por cada 100 mexicanos?

In [6]:
beta_hat : np.array = np.dot(XTX_inv, XTY)
beta_hat

array([[  87.3917682],
       [  -1.2943784],
       [ -81.945232 ],
       [-268.7237298],
       [  46.591608 ]])

In [10]:
coef_X4: float = beta_hat[4, 0]
coef_X4

46.591607999999994

# Ejercicio 2

Si calculas la matriz de $var - cov(\hat{\beta}) = \sigma^2 (X^T X)^{-1}$. El estimador de la varianza homoscedastica $\sigma^2$ es: $9,131.8432$ y la media de las ventas de unidades USB flash portátiles (en miles) es $80$. Calcule el error estándar del coeficiente asociado a la variable las computadoras personales de escritorio vendidas (en millones de unidades),


In [19]:
sigma_squared: float = 9_131.8432
mean_sales: float = 80

cov_beta = np.cov(beta_hat, rowvar=False)

np.dot(sigma_squared, XTX_inv) - cov_beta

array([[  -684.45772486, -19957.21279846, -26874.21874873,
        -18093.8601935 , -20415.26605337],
       [-19957.21279846, -19806.44606723, -19755.12510844,
        -19893.83780665, -19802.88464838],
       [-26874.21874873, -19755.12510844, -16555.78384332,
        -20746.3866878 , -19632.75840956],
       [-18093.8601935 , -19893.83780665, -20746.3866878 ,
         -4249.9859023 , -20413.074411  ],
       [-20415.26605337, -19802.88464838, -19632.75840956,
        -20413.074411  , -19752.11160019]])

In [13]:
sigma_squared * XTX_inv

array([[ 1.91240887e+04, -1.48666407e+02, -7.06567236e+03,
         1.71468620e+03, -6.06719662e+02],
       [-1.48666407e+02,  2.10032394e+00,  5.34212827e+01,
        -8.52914155e+01,  5.66174278e+00],
       [-7.06567236e+03,  5.34212827e+01,  3.25276255e+03,
        -9.37840297e+02,  1.75787982e+02],
       [ 1.71468620e+03, -8.52914155e+01, -9.37840297e+02,
         1.55585605e+04, -6.04528020e+02],
       [-6.06719662e+02,  5.66174278e+00,  1.75787982e+02,
        -6.04528020e+02,  5.64347910e+01]])

C:\Users\Anony\AppData\Local\Temp\ipykernel_18672\4109161073.py:1: RuntimeWarning: Degrees of freedom <= 0 for slice
  np.cov(beta_hat)


array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

# Ejercicio 3

Obtén el pronóstico de ventas en miles de unidades de USB para un nivel de 12,000,000 de computadoras de escritorio, 1,000,000 de unidades vendidas de computadoras portátiles, el porcentaje en el aumento porcentual en el precio del software es del 70% y se cuenta con 70  computadoras  por cada 100 mexicanos.